version: '3.8'

services:
  bedrock-doc-search:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./datasets:/app/datasets
      - ./vectorstore:/app/vectorstore
      - ~/.aws:/root/.aws:ro  # ホストのAWS設定をコンテナにマウント
    command: tail -f /dev/null  # コンテナを常時稼働させる